#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
 export OS_VARIANT=Mac
 export OS_VERSION="$OSTYPE"
else
 export OS_VARIANT=`lsb_release -i | cut -f2`
 export OS_VERSION=`lsb_release -r | cut -f2`
 fi
export MATHEMATICA=`which mathematica`
export TERMINAL=`which lxterminal`
if [ "$TERMINAL" = "" ]; then
 export TERMINAL=`which lxterm`
 fi
if [ "$TERMINAL" = "" ]; then
 export TERMINAL=`which xterm`
 fi
if [ "$TERMINAL" = "" ]; then
 export TERMINAL=`which gnome-terminal`
 fi
