#!/bin/bash

# This script can be called from anywhere if MYPATH is correctly set.
. "$MYPATH"/helper/detect
. "$MYPATH"/helper/qepcad

# This will be used later.
kill_descendant_processes() {
# Taken from https://stackoverflow.com/a/26966800/1044586
    local pid="$1"
    local and_self="${2:-false}"
    if children="$(pgrep -P "$pid")"; then
        for child in $children; do
            kill_descendant_processes "$child" true
        done
    fi
    if [[ "$and_self" == true ]]; then
        kill -9 "$pid"
    fi
}

attempt() {
 FOLDER="$1"
 REALGEOM="$FOLDER/realgeom"
 test -x "$MYPATH"/$REALGEOM || return 1
 echo -n "Starting local RealGeom server on port 8765..."
 if [ "$OS_VARIANT" = "Mac" ]; then
  echo "#!/bin/bash
   export JAVA_HOME=\"$JAVA_HOME\"
   export qe=\"$qe\"
   export PATH=\"$PATH\"
   cd \"$MYPATH\"
   cd \"$FOLDER\"
   ./realgeom -s" > start-realgeom.command
  chmod 755 start-realgeom.command
  open start-realgeom.command
  sleep 2
  REALGEOM_PID=`pgrep -n bash`
 else
  if [ "$TERMINAL" = "" ]; then
   echo "No terminal found. Please install xterm or a compatible one"
   exit 1
   fi
  $TERMINAL -e "cd \"$MYPATH\"; cd \"$FOLDER\"; ./realgeom -s" 2>/dev/null &
  REALGEOM_PID=$!
  fi
 while ! nc -z localhost 8765 && kill -0 $REALGEOM_PID ; do sleep 1; echo -n "."; done
 nc -z localhost 8765 || {
  echo "No realgeom server can be found, expect problems with RealGeomWS"
  }
 echo
 return 0
}

attempt realgeom/bin || attempt realgeom/build/install/realgeom/bin
