#!/bin/bash

# This script can be called from anywhere.
. "$MYPATH"/helper/detect
. "$MYPATH"/helper/qepcad

REALGEOM=realgeom/build/install/realgeom/bin/realgeom
test -x "$MYPATH"/$REALGEOM
echo -n "Starting local RealGeom server on port 8765..."
$TERMINAL -e "cd \"$MYPATH\"; cd realgeom; ./gradlew run --args=\"-s\"" 2>/dev/null &
export REALGEOM_PID=$!
while ! nc -z localhost 8765 && kill -0 $REALGEOM_PID ; do sleep 1; echo -n "."; done
nc -z localhost 8765 || echo "No realgeom server can be found, expect problems with RealGeomWS"
echo
