#!/bin/bash
set -e
# We assume that MYPATH is correctly set.

tarski="$MYPATH/realgeom/tarski"
test -x "$tarski/interpreter/bin/tarski.exe" && export PATH="$PATH:$tarski/interpreter/bin" || \
 test -x "$tarski/bin/tarski" && export PATH="$PATH:$tarski/bin" || true
