#!/bin/bash
. helper/detect
mkdir -p fork
cd fork
test -d geogebra || git clone --depth 1 https://github.com/kovzol/geogebra
cd geogebra
git pull
cd ../..
test -d realgeom || git clone --depth 1 https://github.com/kovzol/realgeom
cd realgeom
git pull
cd ../fork/geogebra
