#!/bin/bash -x

# This script can be called from anywhere.
MYBASENAME=`perl -MCwd -e 'print Cwd::abs_path shift' "$0"`
MYPATH=`dirname "$MYBASENAME"`

. helper/common
. helper/qepcad
. helper/update

./gradlew $GRADLE_OPTIONS :desktop:installDist
cd ../..

if [ "$OS_VARIANT" != "Raspbian" ]; then
 # Compile QEPCAD:
 cd realgeom/qepcad/saclib
 export saclib=`pwd`
 cd bin
 ./sconf && ./mkproto && ./mkmake && ./mklib all
 cd ../..
 cd qepcad/qesource
 make
 if [ "$OS_VARIANT" != "Mac" ]; then
  # Use the non-optimized version:
  cd bin
  test -x qepcad-unstable || {
   mv qepcad qepcad-unstable && mv qepcadd qepcad # TODO: do this only if gcc >= 8.3.0
   }
  cd ..
  fi
 cd ../../../..
 fi

cd realgeom
./gradlew $GRADLE_OPTIONS installDist
LIBDIR=lib
if [ "$OS_VARIANT" = Raspbian ]; then
 # FIXME: This is hardcoded.
 LIBDIR=/opt/Wolfram/WolframEngine/12.0/SystemFiles/Links/JLink/SystemFiles/Libraries/Linux-ARM
 fi
cp $LIBDIR/*.so build/install/realgeom/lib
cd ..

if [ "$OS_VARIANT" = Raspbian ]; then
 rm fork/geogebra/desktop/build/install/desktop/lib/*{amd64,windows,i586,mac}*.jar || true
 fi
