#!/bin/bash

# This script can be called from anywhere.
MYBASENAME=`perl -MCwd -e 'print Cwd::abs_path shift' "$0"`
MYPATH=`dirname "$MYBASENAME"`

. helper/common
. helper/update

if [ "$OS_VARIANT" = Windows ]; then
 export TERM=dumb # ...otherwise Gradle produces garbled output
 fi

# Compile GeoGebra
rm -f desktop/build/*.dll # On Windows some cleanup is forced
./gradlew $GRADLE_OPTIONS :desktop:installDist
cd ../..

# Compile RealGeom:
cd realgeom
./gradlew $GRADLE_OPTIONS installDist
LIBDIR=lib
if [ "$OS_VARIANT" = Raspbian ]; then
 # FIXME: This is hardcoded.
 LIBDIR=/opt/Wolfram/WolframEngine/13.1/SystemFiles/Links/JLink/SystemFiles/Libraries/Linux-ARM
 fi
cp $LIBDIR/*.so build/install/realgeom/lib
cd ..

if [ "$OS_VARIANT" = Raspbian ]; then
 rm fork/geogebra/desktop/build/install/desktop/lib/*{amd64,windows,i586,mac}*.jar || true
 fi
