#!/bin/bash
. helper/common
WARDIR=fork/geogebra/web/war
test -r $WARDIR/web3d/web3d.nocache.js
DISTDIR=dist/$PACKAGE_NAME6
rm -fr $DISTDIR
mkdir -p $DISTDIR
cp $WARDIR/classic.html $DISTDIR/index.html
cp $WARDIR/giacggb.wasm $DISTDIR # Workaround, temporary
cp -ur $WARDIR/web3d $DISTDIR
ZIPFILE=$PACKAGE_NAME6.zip
rm -f dist/$ZIPFILE
cd dist
zip -9r $ZIPFILE $PACKAGE_NAME6
