#!/bin/bash
# This script can be called from anywhere.
MYBASENAME=`perl -MCwd -e 'print Cwd::abs_path shift' "$0"`
MYPATH=`dirname "$MYBASENAME"`

. helper/common
. helper/qepcad

BUNDLE=0

usage() {
 echo "$0 - creates a GeoGebra Discovery Classic 5 package"
 echo "Usage: $0 [options] [scenario]"
 echo " where [options] can be:"
 echo "  -h          this help"
 echo "  -j          add Java Runtime Environment from \"$JAVA_HOME\" to the bundle"
 echo " [scenario] can be:"
 echo "  win         create Windows package"
 echo "By default the scenario is to create a Linux package."
 exit 0
 }

while getopts "jh" OPT; do
 case $OPT in
  j)
   BUNDLE=1
   ;;
  h)
   usage
   ;;
  \?)
   echo "Invalid option: $OPTARG" 1>&2
   exit 1
   ;;
 esac
done

# Put name of the filters into $@
shift $((OPTIND-1))


test -x fork/geogebra/desktop/build/install/desktop/bin/desktop
rm -fr dist/$PACKAGE_NAME
mkdir -p dist/$PACKAGE_NAME/geogebra
rsync -ur fork/geogebra/desktop/build/install/desktop dist/$PACKAGE_NAME/geogebra
# Cross-platform deployment (from Linux to Windows only)
if [ "$1" = win ]; then
 for i in linux mac; do
  rm -f dist/$PACKAGE_NAME/geogebra/desktop/lib/*$i*.jar
  done
 rm -f dist/$PACKAGE_NAME/geogebra/desktop/bin/desktop
 echo "@echo Welcome to $SOFTWARE_NAME
@echo Starting realgeom server...
@cd realgeom\\bin
@start \"realgeom\" realgeom -s
@cd ..\\..
:c
@netstat /a /n | findstr 8765 | findstr LISTENING
@if %ERRORLEVEL%==0 goto :ggstart
@ping 127.0.0.1 -n 2 > nul
@goto :c
:ggstart
@echo Starting GeoGebra...
@call geogebra\\desktop\\bin\\desktop.bat --realgeomws=remoteurl:http\\://localhost\\:8765,cas:qepcad,timeout:10 %*
@taskkill /FI \"WindowTitle eq realgeom*\" /T /F" > dist/$PACKAGE_NAME/GeoGebra-Discovery.bat
 mkdir -p dist/$PACKAGE_NAME/realgeom/bin
 cp bin/qepcad.exe dist/$PACKAGE_NAME/realgeom/bin
 cp $qe/bin/qepcad.help dist/$PACKAGE_NAME/realgeom/bin
 # Copy installed version of realgeom in the .zip
 cd realgeom
 ./gradlew installDist
 rsync -ur build/install/realgeom ../dist/$PACKAGE_NAME
 cd ..
 rm dist/$PACKAGE_NAME/realgeom/bin/realgeom
 rm dist/$PACKAGE_NAME/realgeom/lib/{*linux*,*macosx*}
 # End of copying
 ZIPNAME=$PACKAGE_NAME-Windows

else
# Non-cross-platform deployment
test -d realgeom && {
 # Copy installed version of realgeom in the .zip
 cd realgeom
 ./gradlew installDist
 rsync -ur build/install/realgeom ../dist/$PACKAGE_NAME
 cd ..
 rm dist/$PACKAGE_NAME/realgeom/bin/realgeom.bat
 rm dist/$PACKAGE_NAME/realgeom/lib/*windows*
 if [ "$OS_VARIANT" != Mac ]; then
  cp realgeom/build/install/realgeom/lib/*.so dist/$PACKAGE_NAME/realgeom/lib
  fi
 # End of copying
 if [ "$OS_VARIANT" != Raspbian ]; then
  mkdir -p dist/$PACKAGE_NAME/realgeom/qepcad/qepcad/qesource/bin
  cp $qe/bin/{qepcad,qepcad.help} dist/$PACKAGE_NAME/realgeom/qepcad/qepcad/qesource/bin
  mkdir -p dist/$PACKAGE_NAME/realgeom/tarski/bin
  cp realgeom/tarski/bin/tarski dist/$PACKAGE_NAME/realgeom/tarski/bin
  fi
 }
mkdir -p dist/$PACKAGE_NAME/helper
cp helper/{detect,qepcad,start-realgeom,tarski} dist/$PACKAGE_NAME/helper
rm -f dist/$PACKAGE_NAME/geogebra/desktop/bin/desktop.bat

if [ $BUNDLE = 1 -a "$JAVA_HOME" != "" ]; then
 mkdir dist/$PACKAGE_NAME/jre
 rsync -ur "$JAVA_HOME"/* dist/$PACKAGE_NAME/jre
 fi
if [ "$OS_VARIANT" = Raspbian ]; then
 for i in windows mac i586 amd64 libpxcc zspace; do
  rm -f dist/$PACKAGE_NAME/geogebra/desktop/lib/*$i*.jar
  rm -f dist/$PACKAGE_NAME/realgeom/lib/*$i*.jar
  done
 ZIPNAME=$PACKAGE_NAME-RaspberryPi
else
 if [ "$OS_VARIANT" = Mac ]; then
  for i in windows linux i586 amd64 libpxcc zspace; do
   rm -f dist/$PACKAGE_NAME/geogebra/desktop/lib/*$i*.jar
   rm -f dist/$PACKAGE_NAME/realgeom/lib/*$i*.jar
   done
  ZIPNAME=$PACKAGE_NAME-Mac
 else
  for i in windows mac i586 arm libpxcc zspace; do
   rm -f dist/$PACKAGE_NAME/geogebra/desktop/lib/*$i*.jar
   rm -f dist/$PACKAGE_NAME/realgeom/lib/*$i*.jar
   done
  ZIPNAME=$PACKAGE_NAME-Linux64
  fi
 fi
# Linux startup shell
echo "#!/bin/bash

# This script can be called from anywhere.
MYBASENAME=\`perl -MCwd -e 'print Cwd::abs_path shift' \"\$0\"\`
MYPATH=\`dirname \"\$MYBASENAME\"\`

echo \"Welcome to $SOFTWARE_NAME\"
. \"\$MYPATH\"/helper/detect
. \"\$MYPATH\"/helper/qepcad
. \"\$MYPATH\"/helper/tarski
test -x \"\$MYPATH\"/jre && export JAVA_HOME=\"\`perl -MCwd -e 'print Cwd::abs_path shift' \"\$MYPATH\"/jre\`\"
. \"\$MYPATH\"/helper/start-realgeom
echo -n \"Launching GeoGebra...\"
echo
if [ \"\$MATHEMATICA\" = \"\" ]; then
 CAS=tarski
else
 CAS=mathematica
 fi
\"\$MYPATH\"/geogebra/desktop/bin/desktop --realgeomws=remoteurl:http\\://localhost\\:8765,cas:\$CAS,timeout:10 \"\$@\"
echo \"GeoGebra session ended.\"
echo \"Stopping RealGeom session...\"
kill_descendant_processes \$REALGEOM_PID
kill_descendant_processes \$\$" > dist/$PACKAGE_NAME/GeoGebra-Discovery
chmod 755 dist/$PACKAGE_NAME/GeoGebra-Discovery
fi # End of non-cross-platform deployment

# Common parts in all types of deployments
if [ $BUNDLE = 1 ]; then
 ZIPNAME=$ZIPNAME-withJava
 fi
ZIPNAME=$ZIPNAME.zip
cd dist
rm -f $ZIPNAME
zip -9r $ZIPNAME $PACKAGE_NAME
