#!/bin/bash
. helper/common

BUNDLE=0

usage() {
 echo "$0 - creates a GeoGebra Discovery Classic 5 package"
 echo "Usage: $0 [options] [scenario]"
 echo " where [options] can be:"
 echo "  -h          this help"
 echo "  -j          add Java Runtime Environment from \"$JAVA_HOME\" to the bundle"
 echo " [scenario] can be:"
 echo "  win         create Windows package"
 echo "By default the scenario is to create a Linux package."
 exit 0
 }

while getopts "jh" OPT; do
 case $OPT in
  j)
   BUNDLE=1
   ;;
  h)
   usage
   ;;
  \?)
   echo "Invalid option: $OPTARG" 1>&2
   exit 1
   ;;
 esac
done

# Put name of the filters into $@
shift $((OPTIND-1))


test -x fork/geogebra/desktop/build/install/desktop/bin/desktop
rm -fr dist/$PACKAGE_NAME
mkdir -p dist/$PACKAGE_NAME/geogebra
rsync -ur fork/geogebra/desktop/build/install/desktop dist/$PACKAGE_NAME/geogebra
# Cross-platform deployment (from Linux to Windows only)
if [ "$1" = win ]; then
 for i in linux mac; do
  rm -f dist/$PACKAGE_NAME/geogebra/desktop/lib/*$i*.jar
  done
 rm -f dist/$PACKAGE_NAME/geogebra/desktop/bin/desktop
 echo "@echo Welcome to $SOFTWARE_NAME
@geogebra\\desktop\\\\bin\\desktop.bat %*" > dist/$PACKAGE_NAME/GeoGebra-Discovery.bat
 ZIPNAME=$PACKAGE_NAME-Windows

else
# Non-cross-platform deployment
test -d realgeom && {
 rsync -ur --exclude qepcad realgeom dist/$PACKAGE_NAME
 mkdir -p dist/$PACKAGE_NAME/realgeom/qepcad/qesource/bin
 cp realgeom/qepcad/qesource/bin/{qepcad,qepcad.help} dist/$PACKAGE_NAME/realgeom/qepcad/qesource/bin
 }
mkdir -p dist/$PACKAGE_NAME/helper
cp helper/{detect,qepcad,start-realgeom} dist/$PACKAGE_NAME/helper
rm -f dist/$PACKAGE_NAME/geogebra/desktop/bin/desktop.bat

if [ $BUNDLE = 1 -a "$JAVA_HOME" != "" ]; then
 mkdir dist/$PACKAGE_NAME/jre
 rsync -ur "$JAVA_HOME"/* dist/$PACKAGE_NAME/jre
 fi
if [ "$OS_VARIANT" = Raspbian ]; then
 for i in windows mac i586 amd64 libpxcc zspace; do
  rm -f dist/$PACKAGE_NAME/geogebra/desktop/lib/*$i*.jar
  done
 ZIPNAME=$PACKAGE_NAME-RaspberryPi
else
 if [ "$OS_VARIANT" = Mac ]; then
  for i in windows linux i586 amd64 libpxcc zspace; do
   rm -f dist/$PACKAGE_NAME/geogebra/desktop/lib/*$i*.jar
   done
  ZIPNAME=$PACKAGE_NAME-Mac
 else
  for i in windows mac i586 arm libpxcc zspace; do
   rm -f dist/$PACKAGE_NAME/geogebra/desktop/lib/*$i*.jar
   done
  ZIPNAME=$PACKAGE_NAME-Linux64
  fi
 fi
# Linux startup shell
echo "#!/bin/bash

# This script can be called from anywhere.
MYBASENAME=\`perl -MCwd -e 'print Cwd::abs_path shift' \"\$0\"\`
MYPATH=\`dirname \"\$MYBASENAME\"\`

echo \"Welcome to $SOFTWARE_NAME\"
. \"\$MYPATH\"/helper/detect
. \"\$MYPATH\"/helper/qepcad
. \"\$MYPATH\"/helper/start-realgeom
echo -n \"Launching GeoGebra...\"
test -x \"\$MYPATH\"/jre && export JAVA_HOME=\"\`perl -MCwd -e 'print Cwd::abs_path shift' \"\$MYPATH\"/jre\`\"
echo
\"\$MYPATH\"/geogebra/desktop/bin/desktop --realgeomws=remoteurl:http\\://localhost\\:8765 \"\$@\"
echo \"GeoGebra session ended.\"
echo \"Stopping RealGeom session...\"
kill \$REALGEOM_PID" > dist/$PACKAGE_NAME/GeoGebra-Discovery
chmod 755 dist/$PACKAGE_NAME/GeoGebra-Discovery
fi # End of non-cross-platform deployment

# Common parts in all types of deployments
if [ $BUNDLE = 1 ]; then
 ZIPNAME=$ZIPNAME-withJava
 fi
ZIPNAME=$ZIPNAME.zip
cd dist
rm -f $ZIPNAME
zip -9r $ZIPNAME $PACKAGE_NAME
