#!/bin/sh -x
set -e
. include/detect
if [ "$LINUX_VARIANT" = Raspbian ]; then
 exit 0
 fi
# Linux (Ubuntu 18.04)
test -x buildtools/jbr/bin/java && exit 0
JDK_TGZ=jbr-11_0_4-linux-x64.tar.gz
JDK_URL=http://dev.geogebra.org/download/installer/jdk/$JDK_TGZ
mkdir -p buildtools
cd buildtools
wget -c -N $JDK_URL
tar xzf $JDK_TGZ
