#!/bin/sh -x
set -e
test -x buildtools/jbr/bin/java && exit 0
JDK_TGZ=jbr-11_0_4-linux-x64.tar.gz
JDK_URL=http://dev.geogebra.org/download/installer/jdk/$JDK_TGZ
mkdir -p buildtools
cd buildtools
wget $JDK_URL
tar xzf $JDK_TGZ
