#!/bin/bash

# This script can be called from anywhere.
MYBASENAME=`perl -MCwd -e 'print Cwd::abs_path shift' "$0"`
MYPATH=`dirname "$MYBASENAME"`
. "$MYPATH"/helper/detect

BINDIR=fork/geogebra/desktop/build/install/desktop/bin
test -r "$MYPATH"/$BINDIR/desktop

if [ "$OS_VARIANT" = Mac ]; then
 export JAVA_HOME=`perl -MCwd -e 'print Cwd::abs_path shift' buildtools/jbrsdk/Contents/Home`
else
 if [ "$OS_VARIANT" != Raspbian ]; then
  if [ "$OS_VARIANT" != Windows ]; then
   export JAVA_HOME=`perl -MCwd -e 'print Cwd::abs_path shift' buildtools/jbr`
   else
    export JAVA_HOME=`find /c/Program\ Files\/Microsoft/jdk* | sort | head -1`
   fi
  fi
 fi

export MYPATH
REALGEOMWS=""
if [ "$MATHEMATICA" = "" ] ; then
 CAS=tarski
else
 CAS=mathematica
 fi
# realgeom will be started only on Rasbian:
if [ "$OS_VARIANT" = Raspbian ]; then
 . "$MYPATH"/helper/start-realgeom
 REALGEOMWS="--realgeomws=remoteurl:http\\://localhost\\:8765,cas:$CAS,timeout:10"
 fi

if [ "$REALGEOMWS" != "" ]; then
 echo -n "Launching GeoGebra..."
 fi
export JAVA_OPTS="-Djava.library.path=\"$MYPATH\"/fork/geogebra/desktop/build"
$MYPATH/$BINDIR/desktop $REALGEOMWS "$@"

if [ "$REALGEOMWS" != "" ]; then
 echo "GeoGebra session ended."
 echo "Stopping RealGeom session..."
 kill_descendant_processes $REALGEOM_PID
 kill_descendant_processes $$
 fi
