#!/bin/bash -x

# This script can be called from anywhere.
MYBASENAME=`perl -MCwd -e 'print Cwd::abs_path shift' "$0"`
MYPATH=`dirname "$MYBASENAME"`
. "$MYPATH"/helper/detect

BINDIR=fork/geogebra/desktop/build/install/desktop/bin
test -r "$MYPATH"/$BINDIR/desktop

export MYPATH
. "$MYPATH"/helper/start-realgeom

if [ "$OS_VARIANT" = Mac ]; then
 export JAVA_HOME=`perl -MCwd -e 'print Cwd::abs_path shift' buildtools/jbrsdk/Contents/Home`
 fi

echo -n "Launching GeoGebra..."
if [ "$MATHEMATICA" != "" ]; then
 $MYPATH/$BINDIR/desktop --realgeomws=remoteurl:http\\://localhost\\:8765 "$@"
else
 $MYPATH/$BINDIR/desktop "$@"
 fi

echo "GeoGebra session ended."

if [ "$MATHEMATICA" != "" ]; then
 echo "Stopping RealGeom session..."
 kill $REALGEOM_PID
 fi
