#!/bin/sh -x
. include/detect

BINDIR=fork/geogebra/desktop/build/install/desktop/bin
test -r $BINDIR/desktop

if [ "$MATHEMATICA" != "" ]; then
 REALGEOM=realgeom/build/install/realgeom/bin/realgeom
 test -x $REALGEOM
 echo -n "Starting local RealGeom server on port 8765..."
 $TERMINAL -e "cd realgeom; ./gradlew run --args=\"-s\"" 2>/dev/null &
 REALGEOM_PID=$!
 while ! nc -z localhost 8765; do sleep 1; echo -n "."; done
 echo
 fi

echo -n "Launching GeoGebra..."
cd $BINDIR
if [ "$MATHEMATICA" != "" ]; then
 ./desktop --realgeomws=remoteurl:http\\://localhost\\:8765 "$@"
else
 ./desktop "$@"
 fi

echo "GeoGebra session ended."

if [ "$MATHEMATICA" != "" ]; then
 echo "Stopping RealGeom session..."
 kill $REALGEOM_PID
 fi
