name: geogebra-discovery
architectures:
  - build-on: amd64
base: core20
version: '5.0.641.0'
summary: An experimental version of GeoGebra
description: |
  GeoGebra Discovery is an experimental version of GeoGebra.
  It contains some bleeding edge features of GeoGebra that are
  under heavy development and therefore not intended for every day use yet,
  so they are not included in the official GeoGebra version.

grade: stable

# If this is changed to classic, some non-working features (save/load) do work:
confinement: strict
# confinement: classic

apps:
  geogebra-discovery:
    command: bin/GeoGebra-Discovery
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-16-openjdk-amd64
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/x86_64-linux-gnu/dri
    plugs:
      - x11
      - home
      - network
      - desktop
      - desktop-legacy
      - opengl
      - wayland

parts:
  geogebra-discovery:
    source: https://github.com/kovzol/geogebra-discovery.git
    build-packages: [wget, rsync, lsb-release, zip, default-jdk]
    stage-packages:
      - libfreetype6
      - libpng16-16
      - libpango-1.0-0
      - libxext6
      - libxrender1
      - libgtk-3-0
      - libxtst6
      - libgl1
      - libgl1-mesa-dri
      - libgtk2.0-0
      - libasound2
      - lsb-release
      - openjdk-16-jre
    plugin: dump
    override-build: |
      ./build5 && ./deploy5 && mkdir -p ../install/bin && cp -a dist/GeoGebra-Discovery-*/* ../install/bin
    stage:
      - bin
      - usr
