#!/bin/sh
set -e
. include/detect
if [ "$LINUX_VARIANT" = Raspbian ]; then
 JDK_REL=/usr/lib/jvm/java-11-openjdk-armhf
 export GRADLE_OPTIONS="-Dorg.gradle.jvmargs=-Xmx2000m -DXX:MaxMetaspaceSize=2000m"
else
 JDK_REL=`pwd`/buildtools/jbr
 fi
test -x $JDK_REL/bin/java
export JAVA_HOME=$JDK_REL

GGB_VERSION=`cat fork/geogebra/common/src/main/java/org/geogebra/common/GeoGebraConstants.java |\
 grep " VERSION_STRING = " | awk '{print $7}' | sed s/\"//g | sed s/";"//`
TODAY=`LANG=C; date +%Y%b%d`
SOFTWARE_NAME="GeoGebra Discovery $TODAY (based on GeoGebra $GGB_VERSION)"
PACKAGE_NAME="GeoGebra-Discovery-$GGB_VERSION-$TODAY"
export GGB_VERSION SOFTWARE_NAME PACKAGE_NAME
