#!/bin/sh
export LINUX_VARIANT=`lsb_release -i | cut -f2`
export LINUX_VERSION=`lsb_release -r | cut -f2`
export MATHEMATICA=`which mathematica`
export TERMINAL=`which lxterminal`
if [ "$TERMINAL" = "" ]; then
 export TERMINAL=`which lxterm`
 fi
if [ "$TERMINAL" = "" ]; then
 export TERMINAL=`which xterm`
 fi
