name: build

on: [push]

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: ./get-build-tools
    - name: build5
      run: ./build5
    - name: build6
      run: ./build6

  mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: ./get-build-tools
    - name: build5
      run: ./build5
    - name: build6
      run: ./build6

  windows-clang64:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - name: prerequisites
      uses: msys2/setup-msys2@v2
      with:
        msystem: CLANG64
        update: true
        install: >-
          base-devel
    - name: install-git
      run: choco install git
      shell: cmd
    - name: install-ms-openjdk
      run: choco install microsoft-openjdk --version 11.0.10.9
      shell: cmd
    - name: build5
      run: ./build5
    - name: build6
      run: ./build6
